module.exports = {
  apps: [
    {
      name: 'pars-tabela',
      cwd: '/home/developer/projects/ai-website-builder',
      script: 'npm',
      args: 'start',
      env: {
        PORT: 3000,
        NODE_ENV: 'production',
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      error_file: '/home/developer/logs/pars-tabela-error.log',
      out_file: '/home/developer/logs/pars-tabela-out.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'update-manager',
      cwd: '/home/developer/projects/ai-website-builder',
      script: 'npx',
      args: 'tsx update-server/server.ts',
      env: {
        UPDATE_PORT: 4000,
        NODE_ENV: 'production',
        PROJECT_DIR: '/home/developer/projects/ai-website-builder',
        BACKUP_DIR: '/home/developer/backups',
        UPDATE_ADMIN_PASSWORD: 'pars2024!',
        MAIN_APP_PORT: 3000,
        PM2_APP_NAME: 'pars-tabela',
        GIT_BRANCH: 'main',
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      error_file: '/home/developer/logs/update-manager-error.log',
      out_file: '/home/developer/logs/update-manager-out.log',
      merge_logs: true,
      time: true,
    },
  ],
};
